module.exports = {
  docs: [
    {
      type: 'doc',
      id: 'introduction',
    },
    {
      type: 'category',
      label: 'Javascript',
      collapsed: true,
      items: [
        'javascript/js_index',
        {
          Modules: [
            'javascript/modules/module1_basic',
            'javascript/modules/module2_object',
            'javascript/modules/module3_datatypes',
            'javascript/modules/module4_function',
            'javascript/modules/module5_prototype',
            'javascript/modules/module6_classes',
            'javascript/modules/module7_destruct',
            'javascript/modules/module9_promise',
            'javascript/modules/module10_generator',
            'javascript/modules/module11_module',
            'javascript/modules/module13_set_weakset',
            'javascript/modules/module14_map_weakmap',
            'javascript/modules/module15_async_await',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'ReactJS',
      collapsed: true,
      items: [
        {
          React_Hooks: [
            'reactJS/hooks/hooks_intro',
            {
              'Built-in Hooks': [
                'reactJS/hooks/hooks_state',
                'reactJS/hooks/hooks_effect',
                'reactJS/hooks/hooks_ctx',
                'reactJS/hooks/hooks_memo',
                'reactJS/hooks/hooks_reducer',
              ],
            },
            'reactJS/hooks/hooks_rules',
          ],
        },
        {
          Extra: ['reactJS/extra', 'reactJS/moreTopics'],
        },
        {
          Redux: ['reactJS/redux'],
        },
        'reactJS/react_profile',
        'reactJS/about',
        'reactJS/jsx',
        'reactJS/components',
        'reactJS/lifeCycle',
        'reactJS/propsState',
        'reactJS/events',
        'reactJS/dom',
        'reactJS/styles',
        'reactJS/refs',
        'reactJS/hoc',
        'reactJS/ReactRouter',
        'reactJS/createReactApp',
        'reactJS/lazySuspense',
        'reactJS/testing',
      ],
    },
    {
      type: 'category',
      collapsed: true,
      label: 'React-TypeScript',
      items: [
        'React-TypeScript/basic/editor_integration',
        'React-TypeScript/basic/linting',
        'React-TypeScript/basic/examples',
        {
          Getting_Started: [
            'React-TypeScript/basic/getting-started/function_components',
            'React-TypeScript/basic/getting-started/hooks',
            'React-TypeScript/basic/getting-started/class_components',
            'React-TypeScript/basic/getting-started/default_props',
            'React-TypeScript/basic/getting-started/types_or_interfaces',
            'React-TypeScript/basic/getting-started/basic_type_example',
            'React-TypeScript/basic/getting-started/react_prop_type_example',
            'React-TypeScript/basic/getting-started/get_derived_props_from_state',
            'React-TypeScript/basic/getting-started/forms_and_events',
            'React-TypeScript/basic/getting-started/context',
            'React-TypeScript/basic/getting-started/forward_and_create_ref',
            'React-TypeScript/basic/getting-started/portals',
            'React-TypeScript/basic/getting-started/error_boundaries',
            'React-TypeScript/basic/getting-started/concurrent',
          ],
        },
        {
          Recommended: [
            'React-TypeScript/basic/recommended/codebases',
            'React-TypeScript/basic/recommended/resources',
            'React-TypeScript/basic/recommended/talks',
          ],
        },
        {
          Troubleshooting: [
            'React-TypeScript/basic/troubleshooting/types',
            'React-TypeScript/basic/troubleshooting/operators',
            'React-TypeScript/basic/troubleshooting/utilities',
            'React-TypeScript/basic/troubleshooting/non_ts_files',
            'React-TypeScript/basic/troubleshooting/tsconfig',
            'React-TypeScript/basic/troubleshooting/official_typings_bugs',
          ],
        },
        {
          HOC: [
            'React-TypeScript/hoc/intro',
            'React-TypeScript/hoc/full_example',
            'React-TypeScript/hoc/react_hoc_docs',
            'React-TypeScript/hoc/excluding_props',
          ],
        },
        {
          Migration: [
            'React-TypeScript/migration/intro',
            'React-TypeScript/migration/js_docs',
            'React-TypeScript/migration/from_js',
            'React-TypeScript/migration/from_flow',
          ],
        },
        {
          Advanced: [
            'React-TypeScript/advanced/intro',
            'React-TypeScript/advanced/utility_types',
            'React-TypeScript/advanced/patterns_by_usecase',
            'React-TypeScript/advanced/patterns_by_version',
            'React-TypeScript/advanced/misc_concerns',
            'React-TypeScript/advanced/types_react_api',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Mongo',
      collapsed: true,
      items: ['mongo/mongo'],
    },
    {
      type: 'category',
      label: 'Git',
      collapsed: true,
      items: ['git/git', 'git/gitignore', 'git/gitcommands'],
    },
    {
      type: 'category',
      label: '📋 Interview Hub 📋',
      collapsed: true,
      items: [
        'questions/js',
        'questions/ts',
        'questions/html',
        'questions/style',
        'questions/dom',
        'questions/web',
        'questions/design_pattern',
      ],
    },
    {
      type: 'category',
      label: '💎 Gem Box 💎',
      items: [
        'gemBox/ui_res',
        'gemBox/learning_res',
        'gemBox/hosting_res',
        'gemBox/css_res',
        'gemBox/browser_res',
        'gemBox/react_res',
      ],
    },
  ],
};
