module.exports = {
  docs: [
    {
      type: 'doc',
      id: 'getting-started',
    },
    {
      type: 'category',
      label: 'ReactJS',
      collapsed: false,
      items: [
        'reactJS/about',
        'reactJS/jsx',
        'reactJS/components',
        'reactJS/lifeCycle',
        'reactJS/propsState',
        'reactJS/events',
        'reactJS/dom',
        'reactJS/styles',
        'reactJS/refs',
        'reactJS/hoc',
        'reactJS/ReactRouter',
        'reactJS/createReactApp',
        'reactJS/lazySuspense',
        'reactJS/testing',
        'reactJS/moreTopics',
        'reactJS/redux',
        'reactJS/extra',
      ],
    },
    {
      type: 'category',
      label: 'Jobs',
      collapsed: false,
      items: [
        'job/definition',
        'job/device_assignment',
        'job/arguments',
        'job/scheduling',
        'job/settings',
      ],
    },
    {
      type: 'category',
      label: 'Policies',
      collapsed: false,
      items: ['policies/terms', 'policies/privacy'],
    },
  ],
};
